# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6dfa5fa723506fb4a680132955c83e1a967db5fe7796ed699fb76c4684b1ab39bcb9c5605af18cde7c9c55ed4fe644de2a4718d75cec35fc3981d1d4f9e1ddb

test:
  secret_key_base: f61b37ac002edcbf4dae482e7f6fce7f9587b267a65577fa861070d0d6358c8ec72b36cfcf437aac4b1e86dd1a1f8cf0e39451b113305a485e0c980b85fad7aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
